# Compatible version
mod.mcdep==1.21.11

# Development Version
deps.mc=1.21.11
deps.fabric=0.18.3
deps.fapi=0.140.0+1.21.11
# https://parchmentmc.org/docs/getting-started
#deps.parchment=2025.10.12
deps.rprenames=RPRenames-1.21.11-0.10.2

pub.target.versions=1.21.11
pub.target.platforms=fabric quilt

