mod.mcdep=<=1.21.8 >=1.21.6

deps.mc=1.21.8
deps.fabric=0.17.3
deps.fapi=0.136.0+1.21.8
# https://parchmentmc.org/docs/getting-started
deps.parchment=2025.09.14
deps.rprenames=RPRenames-1.21.8-0.10.1

pub.target.versions=1.21.6 1.21.7 1.21.8
pub.target.platforms=fabric quilt
#pub.libs.required=
#pub.libs.optional=


